Adds auto-favoriting exclusion for workflow libraries
Without testing if a remote URL is a match for the buildData it might log
an error when testing a specific commit against the wrong git repository:
Unexpected error when retrieving changeset
hudson.plugins.git.GitException: Error: git whatchanged --no-abbrev ...
Should fix JENKINS-43400.

Fixing the previous behavior leads to auto-favoriting the author of the
last commit for the workflow library for all builds that contains the
workflow library.

Bumps supported Jenkins to 2.289.3, required by pipeline-groovy-lib.

pipeline-groovy-lib contains duplicate code from deprecated plugin
workflow-cps-global-lib-plugin. Could not add support for both plugins due
the java package being the same.